name: Connect to an AWS role from a GitHub repository

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  AWS_REGION: "us-east-1"  # Change to reflect your AWS Region

jobs:
  AssumeRoleAndCallIdentity:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3  # Ensure compatibility with Python
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1  # Adjusted for compatibility
        with:
          role-to-assume: arn:aws:iam::339713072790:role/GitHubAction-AssumeRoleWithAction
          role-session-name: GitHub_to_AWS_via_FederatedOIDC
          aws-region: ${{ env.AWS_REGION }}
      - name: Get AWS Identity
        run: aws sts get-caller-identity
      - name: Create CodeDeploy Deployment
        run: |
          aws deploy create-deployment \
          --application-name smartCalendar \
          --deployment-group-name dev \
          --deployment-config-name CodeDeployDefault.AllAtOnce \
          --github-location repository=${{ github.repository }},commitId=${{ github.sha }}
